x-app: &app
  build:
    context: ../
    dockerfile: .dev/Dockerfile
    args:
      NODE_MAJOR: '18'
  environment: &env
    NODE_ENV: ${NODE_ENV:-development}
  tmpfs:
    - /tmp
 
services:
  app:
    <<: *app
    command: tail -f /dev/null
    volumes:
      - ..:/app:cached
      - node_modules:/app/node_modules
      - history:/usr/local/hist
      - ./.bashrc:/root/.bashrc:ro

volumes:
  history:
  node_modules:
