version: "3.4"

services:
  rails: &rails
    #build: Dockerfile.dev
    image: ruby:3.1.4
    volumes:
      # That's all the magic!
      - ${PWD}:/${PWD}:cached
      - bundler_data:/usr/local/bundle
    environment:
      HISTFILE: /usr/local/hist/.bash_history
      LANG: C.UTF-8
      PROMPT_DIRTRIM: 2
      PS1: '[\W]\! '
      # Plays nice with gemfiles/*.gemfile files for CI
      BUNDLE_GEMFILE: ${BUNDLE_GEMFILE:-Gemfile}
      NODE_ENV: development
      RAILS_ENV: development
      #BUNDLE_DEPLOYMENT: 0
      #BUNDLE_WITHOUT: ""
    # And that's the second part of the spell
    working_dir: ${PWD}
    ports:
      - 3000:3000
    tmpfs:
      - /tmp
volumes:
  bundler_data:
